'use client'
import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import Header from '@/app/components/Header'
import '../../styles/globals.css'
import {SessionProvider, useSession} from 'next-auth/react'

const inter = Inter({subsets: ['latin']})

const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <SessionProvider>
        <body className={inter.className}>
          <Header />
          {children}
          <footer></footer>
        </body>
      </SessionProvider>
    </html>
  )
}
