'use client'
import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import NavBar from '@/app/components/NavBar'
import '../../styles/globals.css'
import Providers from '@/app/providers'

const inter = Inter({subsets: ['latin']})

const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <Providers>
        <body className={inter.className}>
          <NavBar />
          <div className="bg-gradient-to-r from-gray-800 via-gray-900 to-black min-h-screen py-4 px-4">
            <main className="text-white min-h-screen">{children}</main>
          </div>
          <footer>Footer</footer>
        </body>
      </Providers>
    </html>
  )
}
